### ISSUE TITLE
Simplify installation by using an update site

### ISSUE THREAD

**Issue by imagejan** [spatialsimulator/XitoSBML#2]
Thank you for this nice plugin!
I suggest to setup an [update site ](https://imagej.net/How_to_set_up_and_populate_an_update_site)to make installation as easy as possible. This way, users won't have to run Maven but can simply add the plugin with a single click from within the [updater](https://imagej.net/Updater).

**Comment by funasoul** [comment]
Thank you for your feedback!
We've updated XitoSBML so that it will be installed through ImageJ update site. Please see README.md for detailed instruction.
Thanks!
